# fly.toml app configuration file generated for winter-silence-262 on 2023-05-22T13:13:29-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "winter-silence-262"
primary_region = "ord"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
